language: java
jdk: openjdk12

install: gradle wrapper --gradle-version 5.5

addons:
  sonarcloud:
    organization: "supresswarnings-github"
    token:
          secure: ${SONAR_TOKEN}

script:
    - ./gradlew assemble
    - ./gradlew check
    - ./gradlew codeCoverageReport
    - sonar-scanner

before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/

notifications:
  email: false